// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package clean

var TableNames = struct {
	Operators   string
	Order       string
	OrderDetail string
	Products    string
}{
	Operators:   "operators",
	Order:       "order",
	OrderDetail: "order_detail",
	Products:    "products",
}
