// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package clean

var ViewNames = struct {
	WOrderDetails string
	WOrders       string
}{
	WOrderDetails: "w_order_details",
	WOrders:       "w_orders",
}
