services:
  db:
    image: postgres:${POSTGRES_VERSION}-bookworm
    container_name: work-db
    ports:
      - ${WORK_POSTGRES_PORT}:5432
    environment:
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
      POSTGRES_USER: ${WORK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WORK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WORK_POSTGRES_DB}
    tty: true
    restart: always
    healthcheck:  # コンテナの起動チェック
      test: ["CMD-SHELL", "pg_isready -U $WORK_POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  pgweb:
    image: sosedoff/pgweb
    container_name: work-pgweb
    ports:
      - ${WORK_PGWEB_PORT}:8081
    environment:
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}
      PGWEB_DATABASE_URL: postgres://${WORK_POSTGRES_USER}:${WORK_POSTGRES_PASSWORD}@db:5432/${WORK_POSTGRES_DB}?sslmode=disable
    restart: always
    depends_on:
      db:
        condition: service_healthy
