// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package work

var TableNames = struct {
	CleanDB      string
	GenOrderNo   string
	GenProductID string
}{
	CleanDB:      "clean_db",
	GenOrderNo:   "gen_order_no",
	GenProductID: "gen_product_id",
}
