pkgname: work
output: ../spec/source/work
wipe: true
no-tests: true
add-enum-types: true
no-auto-timestamps: true
add-global-variants: true
psql:
  dbname: sourceDB
  host: 127.0.0.1
  port: 9901
  user: postgres
  pass: password
  sslmode: disable
  schema: work
