// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orders

var TableNames = struct {
	Operators    string
	OrderDetails string
	Orders       string
	Products     string
}{
	Operators:    "operators",
	OrderDetails: "order_details",
	Orders:       "orders",
	Products:     "products",
}
