// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orders

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Operator is an object representing the database table.
type Operator struct { // 担当者ID
	OperatorID string `boil:"operator_id" json:"operator_id" toml:"operator_id" yaml:"operator_id"`
	// 担当者名
	OperatorName string `boil:"operator_name" json:"operator_name" toml:"operator_name" yaml:"operator_name"`
	// 作成日時
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// 更新日時
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	// 作成者
	CreatedBy null.String `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	// 更新者
	UpdatedBy null.String `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`

	R *operatorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L operatorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OperatorColumns = struct {
	OperatorID   string
	OperatorName string
	CreatedAt    string
	UpdatedAt    string
	CreatedBy    string
	UpdatedBy    string
}{
	OperatorID:   "operator_id",
	OperatorName: "operator_name",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	CreatedBy:    "created_by",
	UpdatedBy:    "updated_by",
}

var OperatorTableColumns = struct {
	OperatorID   string
	OperatorName string
	CreatedAt    string
	UpdatedAt    string
	CreatedBy    string
	UpdatedBy    string
}{
	OperatorID:   "operators.operator_id",
	OperatorName: "operators.operator_name",
	CreatedAt:    "operators.created_at",
	UpdatedAt:    "operators.updated_at",
	CreatedBy:    "operators.created_by",
	UpdatedBy:    "operators.updated_by",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod   { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var OperatorWhere = struct {
	OperatorID   whereHelperstring
	OperatorName whereHelperstring
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
	CreatedBy    whereHelpernull_String
	UpdatedBy    whereHelpernull_String
}{
	OperatorID:   whereHelperstring{field: "\"orders\".\"operators\".\"operator_id\""},
	OperatorName: whereHelperstring{field: "\"orders\".\"operators\".\"operator_name\""},
	CreatedAt:    whereHelpertime_Time{field: "\"orders\".\"operators\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"orders\".\"operators\".\"updated_at\""},
	CreatedBy:    whereHelpernull_String{field: "\"orders\".\"operators\".\"created_by\""},
	UpdatedBy:    whereHelpernull_String{field: "\"orders\".\"operators\".\"updated_by\""},
}

// OperatorRels is where relationship names are stored.
var OperatorRels = struct {
	OrderPicOrders     string
	ProductPicProducts string
}{
	OrderPicOrders:     "OrderPicOrders",
	ProductPicProducts: "ProductPicProducts",
}

// operatorR is where relationships are stored.
type operatorR struct {
	OrderPicOrders     OrderSlice   `boil:"OrderPicOrders" json:"OrderPicOrders" toml:"OrderPicOrders" yaml:"OrderPicOrders"`
	ProductPicProducts ProductSlice `boil:"ProductPicProducts" json:"ProductPicProducts" toml:"ProductPicProducts" yaml:"ProductPicProducts"`
}

// NewStruct creates a new relationship struct
func (*operatorR) NewStruct() *operatorR {
	return &operatorR{}
}

func (r *operatorR) GetOrderPicOrders() OrderSlice {
	if r == nil {
		return nil
	}
	return r.OrderPicOrders
}

func (r *operatorR) GetProductPicProducts() ProductSlice {
	if r == nil {
		return nil
	}
	return r.ProductPicProducts
}

// operatorL is where Load methods for each relationship are stored.
type operatorL struct{}

var (
	operatorAllColumns            = []string{"operator_id", "operator_name", "created_at", "updated_at", "created_by", "updated_by"}
	operatorColumnsWithoutDefault = []string{"operator_id", "operator_name"}
	operatorColumnsWithDefault    = []string{"created_at", "updated_at", "created_by", "updated_by"}
	operatorPrimaryKeyColumns     = []string{"operator_id"}
	operatorGeneratedColumns      = []string{}
)

type (
	// OperatorSlice is an alias for a slice of pointers to Operator.
	// This should almost always be used instead of []Operator.
	OperatorSlice []*Operator
	// OperatorHook is the signature for custom Operator hook methods
	OperatorHook func(context.Context, boil.ContextExecutor, *Operator) error

	operatorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	operatorType                 = reflect.TypeOf(&Operator{})
	operatorMapping              = queries.MakeStructMapping(operatorType)
	operatorPrimaryKeyMapping, _ = queries.BindMapping(operatorType, operatorMapping, operatorPrimaryKeyColumns)
	operatorInsertCacheMut       sync.RWMutex
	operatorInsertCache          = make(map[string]insertCache)
	operatorUpdateCacheMut       sync.RWMutex
	operatorUpdateCache          = make(map[string]updateCache)
	operatorUpsertCacheMut       sync.RWMutex
	operatorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var operatorAfterSelectMu sync.Mutex
var operatorAfterSelectHooks []OperatorHook

var operatorBeforeInsertMu sync.Mutex
var operatorBeforeInsertHooks []OperatorHook
var operatorAfterInsertMu sync.Mutex
var operatorAfterInsertHooks []OperatorHook

var operatorBeforeUpdateMu sync.Mutex
var operatorBeforeUpdateHooks []OperatorHook
var operatorAfterUpdateMu sync.Mutex
var operatorAfterUpdateHooks []OperatorHook

var operatorBeforeDeleteMu sync.Mutex
var operatorBeforeDeleteHooks []OperatorHook
var operatorAfterDeleteMu sync.Mutex
var operatorAfterDeleteHooks []OperatorHook

var operatorBeforeUpsertMu sync.Mutex
var operatorBeforeUpsertHooks []OperatorHook
var operatorAfterUpsertMu sync.Mutex
var operatorAfterUpsertHooks []OperatorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Operator) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Operator) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Operator) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Operator) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Operator) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Operator) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Operator) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Operator) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Operator) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range operatorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOperatorHook registers your hook function for all future operations.
func AddOperatorHook(hookPoint boil.HookPoint, operatorHook OperatorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		operatorAfterSelectMu.Lock()
		operatorAfterSelectHooks = append(operatorAfterSelectHooks, operatorHook)
		operatorAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		operatorBeforeInsertMu.Lock()
		operatorBeforeInsertHooks = append(operatorBeforeInsertHooks, operatorHook)
		operatorBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		operatorAfterInsertMu.Lock()
		operatorAfterInsertHooks = append(operatorAfterInsertHooks, operatorHook)
		operatorAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		operatorBeforeUpdateMu.Lock()
		operatorBeforeUpdateHooks = append(operatorBeforeUpdateHooks, operatorHook)
		operatorBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		operatorAfterUpdateMu.Lock()
		operatorAfterUpdateHooks = append(operatorAfterUpdateHooks, operatorHook)
		operatorAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		operatorBeforeDeleteMu.Lock()
		operatorBeforeDeleteHooks = append(operatorBeforeDeleteHooks, operatorHook)
		operatorBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		operatorAfterDeleteMu.Lock()
		operatorAfterDeleteHooks = append(operatorAfterDeleteHooks, operatorHook)
		operatorAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		operatorBeforeUpsertMu.Lock()
		operatorBeforeUpsertHooks = append(operatorBeforeUpsertHooks, operatorHook)
		operatorBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		operatorAfterUpsertMu.Lock()
		operatorAfterUpsertHooks = append(operatorAfterUpsertHooks, operatorHook)
		operatorAfterUpsertMu.Unlock()
	}
}

// One returns a single operator record from the query.
func (q operatorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Operator, error) {
	o := &Operator{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orders: failed to execute a one query for operators")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Operator records from the query.
func (q operatorQuery) All(ctx context.Context, exec boil.ContextExecutor) (OperatorSlice, error) {
	var o []*Operator

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orders: failed to assign all query results to Operator slice")
	}

	if len(operatorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Operator records in the query.
func (q operatorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orders: failed to count operators rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q operatorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orders: failed to check if operators exists")
	}

	return count > 0, nil
}

// OrderPicOrders retrieves all the order's Orders with an executor via order_pic column.
func (o *Operator) OrderPicOrders(mods ...qm.QueryMod) orderQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"orders\".\"orders\".\"order_pic\"=?", o.OperatorID),
	)

	return Orders(queryMods...)
}

// ProductPicProducts retrieves all the product's Products with an executor via product_pic column.
func (o *Operator) ProductPicProducts(mods ...qm.QueryMod) productQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"orders\".\"products\".\"product_pic\"=?", o.OperatorID),
	)

	return Products(queryMods...)
}

// LoadOrderPicOrders allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (operatorL) LoadOrderPicOrders(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOperator interface{}, mods queries.Applicator) error {
	var slice []*Operator
	var object *Operator

	if singular {
		var ok bool
		object, ok = maybeOperator.(*Operator)
		if !ok {
			object = new(Operator)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOperator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOperator))
			}
		}
	} else {
		s, ok := maybeOperator.(*[]*Operator)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOperator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOperator))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &operatorR{}
		}
		args[object.OperatorID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &operatorR{}
			}
			args[obj.OperatorID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`orders.orders`),
		qm.WhereIn(`orders.orders.order_pic in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load orders")
	}

	var resultSlice []*Order
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice orders")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on orders")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for orders")
	}

	if len(orderAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.OrderPicOrders = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &orderR{}
			}
			foreign.R.OrderPicOperator = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.OperatorID == foreign.OrderPic {
				local.R.OrderPicOrders = append(local.R.OrderPicOrders, foreign)
				if foreign.R == nil {
					foreign.R = &orderR{}
				}
				foreign.R.OrderPicOperator = local
				break
			}
		}
	}

	return nil
}

// LoadProductPicProducts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (operatorL) LoadProductPicProducts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeOperator interface{}, mods queries.Applicator) error {
	var slice []*Operator
	var object *Operator

	if singular {
		var ok bool
		object, ok = maybeOperator.(*Operator)
		if !ok {
			object = new(Operator)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeOperator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeOperator))
			}
		}
	} else {
		s, ok := maybeOperator.(*[]*Operator)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeOperator)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeOperator))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &operatorR{}
		}
		args[object.OperatorID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &operatorR{}
			}
			args[obj.OperatorID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`orders.products`),
		qm.WhereIn(`orders.products.product_pic in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load products")
	}

	var resultSlice []*Product
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice products")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for products")
	}

	if len(productAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ProductPicProducts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &productR{}
			}
			foreign.R.ProductPicOperator = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.OperatorID == foreign.ProductPic {
				local.R.ProductPicProducts = append(local.R.ProductPicProducts, foreign)
				if foreign.R == nil {
					foreign.R = &productR{}
				}
				foreign.R.ProductPicOperator = local
				break
			}
		}
	}

	return nil
}

// AddOrderPicOrders adds the given related objects to the existing relationships
// of the operator, optionally inserting them as new records.
// Appends related to o.R.OrderPicOrders.
// Sets related.R.OrderPicOperator appropriately.
func (o *Operator) AddOrderPicOrders(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Order) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OrderPic = o.OperatorID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"orders\".\"orders\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"order_pic"}),
				strmangle.WhereClause("\"", "\"", 2, orderPrimaryKeyColumns),
			)
			values := []interface{}{o.OperatorID, rel.OrderNo}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OrderPic = o.OperatorID
		}
	}

	if o.R == nil {
		o.R = &operatorR{
			OrderPicOrders: related,
		}
	} else {
		o.R.OrderPicOrders = append(o.R.OrderPicOrders, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &orderR{
				OrderPicOperator: o,
			}
		} else {
			rel.R.OrderPicOperator = o
		}
	}
	return nil
}

// AddProductPicProducts adds the given related objects to the existing relationships
// of the operator, optionally inserting them as new records.
// Appends related to o.R.ProductPicProducts.
// Sets related.R.ProductPicOperator appropriately.
func (o *Operator) AddProductPicProducts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Product) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ProductPic = o.OperatorID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"orders\".\"products\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"product_pic"}),
				strmangle.WhereClause("\"", "\"", 2, productPrimaryKeyColumns),
			)
			values := []interface{}{o.OperatorID, rel.ProductID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ProductPic = o.OperatorID
		}
	}

	if o.R == nil {
		o.R = &operatorR{
			ProductPicProducts: related,
		}
	} else {
		o.R.ProductPicProducts = append(o.R.ProductPicProducts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &productR{
				ProductPicOperator: o,
			}
		} else {
			rel.R.ProductPicOperator = o
		}
	}
	return nil
}

// Operators retrieves all the records using an executor.
func Operators(mods ...qm.QueryMod) operatorQuery {
	mods = append(mods, qm.From("\"orders\".\"operators\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"orders\".\"operators\".*"})
	}

	return operatorQuery{q}
}

// FindOperator retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOperator(ctx context.Context, exec boil.ContextExecutor, operatorID string, selectCols ...string) (*Operator, error) {
	operatorObj := &Operator{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"orders\".\"operators\" where \"operator_id\"=$1", sel,
	)

	q := queries.Raw(query, operatorID)

	err := q.Bind(ctx, exec, operatorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orders: unable to select from operators")
	}

	if err = operatorObj.doAfterSelectHooks(ctx, exec); err != nil {
		return operatorObj, err
	}

	return operatorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Operator) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orders: no operators provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(operatorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	operatorInsertCacheMut.RLock()
	cache, cached := operatorInsertCache[key]
	operatorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			operatorAllColumns,
			operatorColumnsWithDefault,
			operatorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(operatorType, operatorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(operatorType, operatorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"orders\".\"operators\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"orders\".\"operators\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orders: unable to insert into operators")
	}

	if !cached {
		operatorInsertCacheMut.Lock()
		operatorInsertCache[key] = cache
		operatorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Operator.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Operator) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	operatorUpdateCacheMut.RLock()
	cache, cached := operatorUpdateCache[key]
	operatorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			operatorAllColumns,
			operatorPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("orders: unable to update operators, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"orders\".\"operators\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, operatorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(operatorType, operatorMapping, append(wl, operatorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to update operators row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orders: failed to get rows affected by update for operators")
	}

	if !cached {
		operatorUpdateCacheMut.Lock()
		operatorUpdateCache[key] = cache
		operatorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q operatorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to update all for operators")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to retrieve rows affected for operators")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OperatorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orders: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), operatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"orders\".\"operators\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, operatorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to update all in operator slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to retrieve rows affected all in update all operator")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Operator) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("orders: no operators provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(operatorColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	operatorUpsertCacheMut.RLock()
	cache, cached := operatorUpsertCache[key]
	operatorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			operatorAllColumns,
			operatorColumnsWithDefault,
			operatorColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			operatorAllColumns,
			operatorPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orders: unable to upsert operators, could not build update column list")
		}

		ret := strmangle.SetComplement(operatorAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(operatorPrimaryKeyColumns) == 0 {
				return errors.New("orders: unable to upsert operators, could not build conflict column list")
			}

			conflict = make([]string, len(operatorPrimaryKeyColumns))
			copy(conflict, operatorPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"orders\".\"operators\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(operatorType, operatorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(operatorType, operatorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orders: unable to upsert operators")
	}

	if !cached {
		operatorUpsertCacheMut.Lock()
		operatorUpsertCache[key] = cache
		operatorUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Operator record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Operator) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orders: no Operator provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), operatorPrimaryKeyMapping)
	sql := "DELETE FROM \"orders\".\"operators\" WHERE \"operator_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to delete from operators")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orders: failed to get rows affected by delete for operators")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q operatorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orders: no operatorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to delete all from operators")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orders: failed to get rows affected by deleteall for operators")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OperatorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(operatorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), operatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"orders\".\"operators\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, operatorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orders: unable to delete all from operator slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orders: failed to get rows affected by deleteall for operators")
	}

	if len(operatorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Operator) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOperator(ctx, exec, o.OperatorID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OperatorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OperatorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), operatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"orders\".\"operators\".* FROM \"orders\".\"operators\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, operatorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orders: unable to reload all in OperatorSlice")
	}

	*o = slice

	return nil
}

// OperatorExists checks if the Operator row exists.
func OperatorExists(ctx context.Context, exec boil.ContextExecutor, operatorID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"orders\".\"operators\" where \"operator_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, operatorID)
	}
	row := exec.QueryRowContext(ctx, sql, operatorID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orders: unable to check if operators exists")
	}

	return exists, nil
}

// Exists checks if the Operator row exists.
func (o *Operator) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OperatorExists(ctx, exec, o.OperatorID)
}
