// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package legacy

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// OrderDetail is an object representing the database table.
type OrderDetail struct { // 受注番号
	OrderNo int `boil:"order_no" json:"order_no" toml:"order_no" yaml:"order_no"`
	// 受注明細番号
	OrderDetailNo int `boil:"order_detail_no" json:"order_detail_no" toml:"order_detail_no" yaml:"order_detail_no"`
	// 商品名
	ProductName string `boil:"product_name" json:"product_name" toml:"product_name" yaml:"product_name"`
	// 受注数
	ReceivingQuantity int `boil:"receiving_quantity" json:"receiving_quantity" toml:"receiving_quantity" yaml:"receiving_quantity"`
	// 出荷済フラグ
	ShippingFlag bool `boil:"shipping_flag" json:"shipping_flag" toml:"shipping_flag" yaml:"shipping_flag"`
	// キャンセルフラグ
	CanceledFlag bool `boil:"canceled_flag" json:"canceled_flag" toml:"canceled_flag" yaml:"canceled_flag"`
	// 販売単価
	SellingPrice int `boil:"selling_price" json:"selling_price" toml:"selling_price" yaml:"selling_price"`
	// 商品原価
	CostPrice int `boil:"cost_price" json:"cost_price" toml:"cost_price" yaml:"cost_price"`

	R *orderDetailR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L orderDetailL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OrderDetailColumns = struct {
	OrderNo           string
	OrderDetailNo     string
	ProductName       string
	ReceivingQuantity string
	ShippingFlag      string
	CanceledFlag      string
	SellingPrice      string
	CostPrice         string
}{
	OrderNo:           "order_no",
	OrderDetailNo:     "order_detail_no",
	ProductName:       "product_name",
	ReceivingQuantity: "receiving_quantity",
	ShippingFlag:      "shipping_flag",
	CanceledFlag:      "canceled_flag",
	SellingPrice:      "selling_price",
	CostPrice:         "cost_price",
}

var OrderDetailTableColumns = struct {
	OrderNo           string
	OrderDetailNo     string
	ProductName       string
	ReceivingQuantity string
	ShippingFlag      string
	CanceledFlag      string
	SellingPrice      string
	CostPrice         string
}{
	OrderNo:           "order_details.order_no",
	OrderDetailNo:     "order_details.order_detail_no",
	ProductName:       "order_details.product_name",
	ReceivingQuantity: "order_details.receiving_quantity",
	ShippingFlag:      "order_details.shipping_flag",
	CanceledFlag:      "order_details.canceled_flag",
	SellingPrice:      "order_details.selling_price",
	CostPrice:         "order_details.cost_price",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var OrderDetailWhere = struct {
	OrderNo           whereHelperint
	OrderDetailNo     whereHelperint
	ProductName       whereHelperstring
	ReceivingQuantity whereHelperint
	ShippingFlag      whereHelperbool
	CanceledFlag      whereHelperbool
	SellingPrice      whereHelperint
	CostPrice         whereHelperint
}{
	OrderNo:           whereHelperint{field: "`order_details`.`order_no`"},
	OrderDetailNo:     whereHelperint{field: "`order_details`.`order_detail_no`"},
	ProductName:       whereHelperstring{field: "`order_details`.`product_name`"},
	ReceivingQuantity: whereHelperint{field: "`order_details`.`receiving_quantity`"},
	ShippingFlag:      whereHelperbool{field: "`order_details`.`shipping_flag`"},
	CanceledFlag:      whereHelperbool{field: "`order_details`.`canceled_flag`"},
	SellingPrice:      whereHelperint{field: "`order_details`.`selling_price`"},
	CostPrice:         whereHelperint{field: "`order_details`.`cost_price`"},
}

// OrderDetailRels is where relationship names are stored.
var OrderDetailRels = struct {
}{}

// orderDetailR is where relationships are stored.
type orderDetailR struct {
}

// NewStruct creates a new relationship struct
func (*orderDetailR) NewStruct() *orderDetailR {
	return &orderDetailR{}
}

// orderDetailL is where Load methods for each relationship are stored.
type orderDetailL struct{}

var (
	orderDetailAllColumns            = []string{"order_no", "order_detail_no", "product_name", "receiving_quantity", "shipping_flag", "canceled_flag", "selling_price", "cost_price"}
	orderDetailColumnsWithoutDefault = []string{"order_no", "order_detail_no", "product_name", "receiving_quantity", "shipping_flag", "canceled_flag", "selling_price", "cost_price"}
	orderDetailColumnsWithDefault    = []string{}
	orderDetailPrimaryKeyColumns     = []string{"order_no", "order_detail_no"}
	orderDetailGeneratedColumns      = []string{}
)

type (
	// OrderDetailSlice is an alias for a slice of pointers to OrderDetail.
	// This should almost always be used instead of []OrderDetail.
	OrderDetailSlice []*OrderDetail
	// OrderDetailHook is the signature for custom OrderDetail hook methods
	OrderDetailHook func(context.Context, boil.ContextExecutor, *OrderDetail) error

	orderDetailQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	orderDetailType                 = reflect.TypeOf(&OrderDetail{})
	orderDetailMapping              = queries.MakeStructMapping(orderDetailType)
	orderDetailPrimaryKeyMapping, _ = queries.BindMapping(orderDetailType, orderDetailMapping, orderDetailPrimaryKeyColumns)
	orderDetailInsertCacheMut       sync.RWMutex
	orderDetailInsertCache          = make(map[string]insertCache)
	orderDetailUpdateCacheMut       sync.RWMutex
	orderDetailUpdateCache          = make(map[string]updateCache)
	orderDetailUpsertCacheMut       sync.RWMutex
	orderDetailUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var orderDetailAfterSelectMu sync.Mutex
var orderDetailAfterSelectHooks []OrderDetailHook

var orderDetailBeforeInsertMu sync.Mutex
var orderDetailBeforeInsertHooks []OrderDetailHook
var orderDetailAfterInsertMu sync.Mutex
var orderDetailAfterInsertHooks []OrderDetailHook

var orderDetailBeforeUpdateMu sync.Mutex
var orderDetailBeforeUpdateHooks []OrderDetailHook
var orderDetailAfterUpdateMu sync.Mutex
var orderDetailAfterUpdateHooks []OrderDetailHook

var orderDetailBeforeDeleteMu sync.Mutex
var orderDetailBeforeDeleteHooks []OrderDetailHook
var orderDetailAfterDeleteMu sync.Mutex
var orderDetailAfterDeleteHooks []OrderDetailHook

var orderDetailBeforeUpsertMu sync.Mutex
var orderDetailBeforeUpsertHooks []OrderDetailHook
var orderDetailAfterUpsertMu sync.Mutex
var orderDetailAfterUpsertHooks []OrderDetailHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *OrderDetail) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *OrderDetail) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *OrderDetail) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *OrderDetail) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *OrderDetail) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *OrderDetail) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *OrderDetail) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *OrderDetail) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *OrderDetail) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range orderDetailAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOrderDetailHook registers your hook function for all future operations.
func AddOrderDetailHook(hookPoint boil.HookPoint, orderDetailHook OrderDetailHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		orderDetailAfterSelectMu.Lock()
		orderDetailAfterSelectHooks = append(orderDetailAfterSelectHooks, orderDetailHook)
		orderDetailAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		orderDetailBeforeInsertMu.Lock()
		orderDetailBeforeInsertHooks = append(orderDetailBeforeInsertHooks, orderDetailHook)
		orderDetailBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		orderDetailAfterInsertMu.Lock()
		orderDetailAfterInsertHooks = append(orderDetailAfterInsertHooks, orderDetailHook)
		orderDetailAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		orderDetailBeforeUpdateMu.Lock()
		orderDetailBeforeUpdateHooks = append(orderDetailBeforeUpdateHooks, orderDetailHook)
		orderDetailBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		orderDetailAfterUpdateMu.Lock()
		orderDetailAfterUpdateHooks = append(orderDetailAfterUpdateHooks, orderDetailHook)
		orderDetailAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		orderDetailBeforeDeleteMu.Lock()
		orderDetailBeforeDeleteHooks = append(orderDetailBeforeDeleteHooks, orderDetailHook)
		orderDetailBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		orderDetailAfterDeleteMu.Lock()
		orderDetailAfterDeleteHooks = append(orderDetailAfterDeleteHooks, orderDetailHook)
		orderDetailAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		orderDetailBeforeUpsertMu.Lock()
		orderDetailBeforeUpsertHooks = append(orderDetailBeforeUpsertHooks, orderDetailHook)
		orderDetailBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		orderDetailAfterUpsertMu.Lock()
		orderDetailAfterUpsertHooks = append(orderDetailAfterUpsertHooks, orderDetailHook)
		orderDetailAfterUpsertMu.Unlock()
	}
}

// One returns a single orderDetail record from the query.
func (q orderDetailQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OrderDetail, error) {
	o := &OrderDetail{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "legacy: failed to execute a one query for order_details")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all OrderDetail records from the query.
func (q orderDetailQuery) All(ctx context.Context, exec boil.ContextExecutor) (OrderDetailSlice, error) {
	var o []*OrderDetail

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "legacy: failed to assign all query results to OrderDetail slice")
	}

	if len(orderDetailAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all OrderDetail records in the query.
func (q orderDetailQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: failed to count order_details rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q orderDetailQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "legacy: failed to check if order_details exists")
	}

	return count > 0, nil
}

// OrderDetails retrieves all the records using an executor.
func OrderDetails(mods ...qm.QueryMod) orderDetailQuery {
	mods = append(mods, qm.From("`order_details`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`order_details`.*"})
	}

	return orderDetailQuery{q}
}

// FindOrderDetail retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOrderDetail(ctx context.Context, exec boil.ContextExecutor, orderNo int, orderDetailNo int, selectCols ...string) (*OrderDetail, error) {
	orderDetailObj := &OrderDetail{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `order_details` where `order_no`=? AND `order_detail_no`=?", sel,
	)

	q := queries.Raw(query, orderNo, orderDetailNo)

	err := q.Bind(ctx, exec, orderDetailObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "legacy: unable to select from order_details")
	}

	if err = orderDetailObj.doAfterSelectHooks(ctx, exec); err != nil {
		return orderDetailObj, err
	}

	return orderDetailObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OrderDetail) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("legacy: no order_details provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(orderDetailColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	orderDetailInsertCacheMut.RLock()
	cache, cached := orderDetailInsertCache[key]
	orderDetailInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			orderDetailAllColumns,
			orderDetailColumnsWithDefault,
			orderDetailColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(orderDetailType, orderDetailMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(orderDetailType, orderDetailMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `order_details` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `order_details` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `order_details` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, orderDetailPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "legacy: unable to insert into order_details")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.OrderNo,
		o.OrderDetailNo,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "legacy: unable to populate default values for order_details")
	}

CacheNoHooks:
	if !cached {
		orderDetailInsertCacheMut.Lock()
		orderDetailInsertCache[key] = cache
		orderDetailInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the OrderDetail.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OrderDetail) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	orderDetailUpdateCacheMut.RLock()
	cache, cached := orderDetailUpdateCache[key]
	orderDetailUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			orderDetailAllColumns,
			orderDetailPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("legacy: unable to update order_details, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `order_details` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, orderDetailPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(orderDetailType, orderDetailMapping, append(wl, orderDetailPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to update order_details row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "legacy: failed to get rows affected by update for order_details")
	}

	if !cached {
		orderDetailUpdateCacheMut.Lock()
		orderDetailUpdateCache[key] = cache
		orderDetailUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q orderDetailQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to update all for order_details")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to retrieve rows affected for order_details")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OrderDetailSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("legacy: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), orderDetailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `order_details` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, orderDetailPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to update all in orderDetail slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to retrieve rows affected all in update all orderDetail")
	}
	return rowsAff, nil
}

var mySQLOrderDetailUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OrderDetail) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("legacy: no order_details provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(orderDetailColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLOrderDetailUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	orderDetailUpsertCacheMut.RLock()
	cache, cached := orderDetailUpsertCache[key]
	orderDetailUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			orderDetailAllColumns,
			orderDetailColumnsWithDefault,
			orderDetailColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			orderDetailAllColumns,
			orderDetailPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("legacy: unable to upsert order_details, could not build update column list")
		}

		ret := strmangle.SetComplement(orderDetailAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`order_details`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `order_details` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(orderDetailType, orderDetailMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(orderDetailType, orderDetailMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "legacy: unable to upsert for order_details")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(orderDetailType, orderDetailMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "legacy: unable to retrieve unique values for order_details")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "legacy: unable to populate default values for order_details")
	}

CacheNoHooks:
	if !cached {
		orderDetailUpsertCacheMut.Lock()
		orderDetailUpsertCache[key] = cache
		orderDetailUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single OrderDetail record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OrderDetail) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("legacy: no OrderDetail provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), orderDetailPrimaryKeyMapping)
	sql := "DELETE FROM `order_details` WHERE `order_no`=? AND `order_detail_no`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to delete from order_details")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "legacy: failed to get rows affected by delete for order_details")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q orderDetailQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("legacy: no orderDetailQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to delete all from order_details")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "legacy: failed to get rows affected by deleteall for order_details")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OrderDetailSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(orderDetailBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), orderDetailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `order_details` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, orderDetailPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "legacy: unable to delete all from orderDetail slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "legacy: failed to get rows affected by deleteall for order_details")
	}

	if len(orderDetailAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OrderDetail) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOrderDetail(ctx, exec, o.OrderNo, o.OrderDetailNo)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OrderDetailSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OrderDetailSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), orderDetailPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `order_details`.* FROM `order_details` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, orderDetailPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "legacy: unable to reload all in OrderDetailSlice")
	}

	*o = slice

	return nil
}

// OrderDetailExists checks if the OrderDetail row exists.
func OrderDetailExists(ctx context.Context, exec boil.ContextExecutor, orderNo int, orderDetailNo int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `order_details` where `order_no`=? AND `order_detail_no`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, orderNo, orderDetailNo)
	}
	row := exec.QueryRowContext(ctx, sql, orderNo, orderDetailNo)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "legacy: unable to check if order_details exists")
	}

	return exists, nil
}

// Exists checks if the OrderDetail row exists.
func (o *OrderDetail) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OrderDetailExists(ctx, exec, o.OrderNo, o.OrderDetailNo)
}
